### ISSUE TITLE
Create a getting started guide

### ISSUE THREAD

**Issue by daniellavoie** [daniellavoie/xcomponent-dev-center#1]
The current [developper reference](https://github.com/xcomponent/xcompoent) of xcomponent offers a complete overview of the platform. However, it's too dense to provide a quick startup for any curious visitor who would like to try out our platform in less than 5 minutes.

# Prerequisites to start with XComponent

* .Net 4.5 Framework
* Visual Studio Community
* RabbitMQ ( is it possible to switch to a rabbit less implementation for GS ?)
* XComponent Runtime with XCStudio

# Objective

* Provide a 5 minutes max Getting Started experience inspired by [Spring Boot](https://projects.spring.io/spring-boot/)

# Problems

* XCStudio and XComponent requires multiple dependencies
* Project boostraping requires a couple of manual steps

# Options

## Option 1 - Provide a XC CLI

The XC CLI would ease developmer experience by automating project bootstraping tasks. For example : 

* `xc install` - Calculates all the prerequisites for XCStudio and install all of them unattended.
* `xc init` - Generate a helloworld project. Could support a `-t template-name` option for custom project templates.

XComponent also aspires to provide a cloud based runtime environment of components. The XC CLI would be able to provide cloud operation commands.

# Initial Example Projects

* Helloworld
* Websocket client

# References

* [Getting Started Web Site](https://daniellavoie.github.io/xcomponent-dev-center/)
* [Contribute to XComponent Dev Center](https://github.com/daniellavoie/xcomponent-dev-center/wiki/Contribute-to-XComponent-Dev-Center)

# Tasks

- [x] Prepare the website infrastructure on Github Pages
- [ ] Define a website template for the getting started guide
- [x] Identify how the Getting Started introduction will be structured
- [ ] Add link to Github
- [ ] Add link to XC CLI binairies
- [ ] Add link to Slack channel
- [ ] Add link to Stackoverflow
